version: '3.8'

services:
  db:
    image: postgres:13-alpine
    env_file: .env
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  ingest-cocktail:
    build: .
    env_file: .env
    depends_on:
      - db
    command: python ingest_cocktaildb.py

  ingest-spoonacular:
    build: .
    env_file: .env
    depends_on:
      - db
    command: python ingest_spoonacular.py

  web:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    # CMD in Dockerfile starts uvicorn

volumes:
  db-data:
